export { default as Main } from "../components/Main";
export { default as WhatReal } from "../components/WhatReal";
// export { default as Products } from "./Newsletter";
export { default as Navbar } from "../components/Navbar";
export { default as FAQ } from "../components/FAQ";
export { default as ComfortSec } from "../components/ComfortSec";
export { default as Banner } from "../components/Banner";
export { default as AboutSec } from "../components/AboutSec";
export { default as ShortAbout } from "../components/ShortAbout";
export { default as RentalFort } from "../components/RentalFort";
export { default as WhyRental } from "../components/WhyRental";
export { default as RentalTypes } from "../components/RentalTypes";
export { default as Newsletter } from "../components/Newsletter";
export { default as SearchFilters } from "../components/SearchFilters";
export { default as City } from "../components/City";
export { default as Sidebar } from "../components/Sidebar";
export { default as MenuItems } from "../components/MenuItems";
export { default as Dropdown } from "../components/Dropdown";
export { default as Submenu } from "../components/Submenu";

export { default as SearchLocation } from "../components/SearchLocation";