export { default as Main } from "../components/Main";
export { default as WhatReal } from "../components/WhatReal";
export { default as Products } from "../pages/Newsletter";
export { default as Navbar } from "../components/Navbar";
export { default as FAQ } from "../components/FAQ";
export { default as ComfortSec } from "../components/ComfortSec";
export { default as Banner } from "../components/Banner";
export { default as AboutSec } from "../components/AboutSec";
export { default as ShortAbout } from "../components/ShortAbout";
